var domainRows = [
  {id: 'Audio'},
  {id: 'Video'},
  {id: 'Camera'},
  {id: 'Launcher'},
  {id: 'Device'},
  {id: 'Clock'},
  {id: 'Notes'},
  {id: 'Weather'},
  {id: 'News'},
  {id: 'FM'},
  {id: 'Whatsapp'},
  {id: 'Calendar'},
  {id: 'Navigation'},
  {id: 'Web'},
  {id: 'Ticket'},
  {id: 'Faq'},
  {id: 'Only4NLU'},
  {id: 'Facebook'},
  {id: 'Translate'},
  {id: 'Vskit'},
  {id: 'Calculator'},
  {id: 'Joke'},
  {id: 'Generic'}
]

var intentRows = [
  {id: 'Audio_MusicPlay', pid: 'Audio'},
  {id: 'Audio_MusicAdd', pid: 'Audio'},
  {id: 'Video_Play', pid: 'Video'},
  {id: 'Camera_SwitchMode', pid: 'Camera'},
  {id: 'Camera_SwitchCamera', pid: 'Camera'},
  {id: 'Camera_TakePhoto', pid: 'Camera'},
  {id: 'Camera_TakeSelfie', pid: 'Camera'},
  {id: 'Camera_TakeVideo', pid: 'Camera'},
  {id: 'Camera_OpenCamera', pid: 'Camera'},
  {id: 'Launcher_AppOpen', pid: 'Launcher'},
  {id: 'Launcher_AppUpdate', pid: 'Launcher'},
  {id: 'Launcher_AppSearch', pid: 'Launcher'},
  {id: 'Launcher_AppDownload', pid: 'Launcher'},
  {id: 'Launcher_AppDelete', pid: 'Launcher'},
  {id: 'Device_SettingsOn', pid: 'Device'},
  {id: 'Device_SettingsOff', pid: 'Device'},
  {id: 'Device_VolumeDecrease', pid: 'Device'},
  {id: 'Device_VolumeIncrease', pid: 'Device'},
  {id: 'Device_VolumeSet', pid: 'Device'},
  {id: 'Device_VolumeMute', pid: 'Device'},
  {id: 'Device_VolumeUnmute', pid: 'Device'},
  {id: 'Device_VolumeMax', pid: 'Device'},
  {id: 'Device_VolumeMin', pid: 'Device'},
  {id: 'Device_BrightnessDecrease', pid: 'Device'},
  {id: 'Device_BrightnessIncrease', pid: 'Device'},
  {id: 'Device_BrightnessSet', pid: 'Device'},
  {id: 'Device_BrightnessMax', pid: 'Device'},
  {id: 'Device_BrightnessMin', pid: 'Device'},
  {id: 'Device_NodisturbON', pid: 'Device'},
  {id: 'Device_NodisturbOff', pid: 'Device'},
  {id: 'Device_Poweroff', pid: 'Device'},
  {id: 'Device_PoweroffYes', pid: 'Device'},
  {id: 'Device_PoweroffNo', pid: 'Device'},
  {id: 'Device_SwitchSystemLanguage', pid: 'Device'},
  {id: 'Device_SchedulePowerOn', pid: 'Device'},
  {id: 'Device_SchedulePowerOff', pid: 'Device'},
  {id: 'Device_ScreenUseTime', pid: 'Device'},
  {id: 'Clock_TimeGet', pid : 'Clock'},
  {id: 'Clock_DateGet', pid : 'Clock'},
  {id: 'Clock_AlarmCheck', pid : 'Clock'},
  {id: 'Clock_AlarmSet', pid : 'Clock'},
  {id: 'Clock_AlarmUnset', pid : 'Clock'},
  {id: 'Clock_AlarmDelete', pid : 'Clock'},
  {id: 'Clock_TimerSet', pid : 'Clock'},
  {id: 'Clock_TimerReplace', pid : 'Clock'},
  {id: 'Clock_TimerKeep', pid : 'Clock'},
  {id: 'Communication_PhoneDial', pid : 'Clock'},
  {id: 'Communication_PhoneRedial', pid : 'Clock'},
  {id: 'Communication_PhoneAnswer', pid : 'Clock'},
  {id: 'Communication_PhoneReject', pid : 'Clock'},
  {id: 'Communication_PhoneCheck', pid : 'Clock'},
  {id: 'Communication_MessageSend', pid : 'Clock'},
  {id: 'Communication_MessageAck', pid : 'Clock'},
  {id: 'Communication_MessageCancel', pid : 'Clock'},
  {id: 'Notes_Show', pid : 'Notes'},
  {id: 'Notes_Add', pid : 'Notes'},
  {id: 'Notes_Delete', pid : 'Notes'},
  {id: 'Weather_Forecast', pid : 'Weather'},
  {id: 'Weather_Temperature', pid : 'Weather'},
  {id: 'News_Play', pid : 'News'},
  {id: 'FM_Modulation', pid : 'FM'},
  {id: 'Whatsapp_MessageSend', pid : 'Whatsapp'},
  {id: 'Whatsapp_MessageAck', pid : 'Whatsapp'},
  {id: 'Whatsapp_MessageCancel', pid : 'Whatsapp'},
  {id: 'Whatsapp_AudioCall', pid : 'Whatsapp'},
  {id: 'Whatsapp_VideoCall', pid : 'Whatsapp'},
  {id: 'Whatsapp_Dynamic', pid : 'Whatsapp'},
  {id: 'Whatsapp_Delete', pid : 'Whatsapp'},
  {id: 'Whatsapp_PhotoSend', pid : 'Whatsapp'},
  {id: 'Whatsapp_PhotoAck', pid : 'Whatsapp'},
  {id: 'Whatsapp_PhotoCancel', pid : 'Whatsapp'},
  {id: 'Calendar_Show', pid : 'Calendar'},
  {id: 'Calendar_Add', pid : 'Calendar'},
  {id: 'Calendar_Delete', pid : 'Calendar'},
  {id: 'Navigation_Start', pid : 'Navigation'},
  {id: 'Navigation_Stop', pid : 'Navigation'},
  {id: 'Navigation_CurrentLocation', pid : 'Navigation'},
  {id: 'Navigation_Search', pid : 'Navigation'},
  {id: 'Web_Search', pid : 'Web'},
  {id: 'Ticket_Reservation',pid: 'Ticket'},
  {id: 'Faq_WhoIAm',pid: 'Faq'},
  {id: 'Faq_WhoYouAre',pid: 'Faq'},
  {id: 'Faq_MissElla',pid: 'Faq'},
  {id: 'Faq_AskSkill',pid: 'Faq'},
  {id: 'Faq_AskSingOrNot',pid: 'Faq'},
  {id: 'Faq_AskGender',pid: 'Faq'},
  {id: 'Faq_AskFather',pid: 'Faq'},
  {id: 'Faq_AskMother',pid: 'Faq'},
  {id: 'Faq_AskAge',pid: 'Faq'},
  {id: 'Faq_HelloElla',pid: 'Faq'},
  {id: 'Generic_DateTypeLocation',pid: 'Only4NLU'},
  {id: 'Generic_DateLocation',pid: 'Only4NLU'},
  {id: 'Generic_DateTime',pid: 'Only4NLU'},
  {id: 'Generic_DateType',pid: 'Only4NLU'},
  {id: 'Generic_CalculateContent',pid: 'Only4NLU'},
  {id: 'Generic_CustomLocation',pid: 'Only4NLU'},
  {id: 'Generic_Time',pid: 'Only4NLU'},
  {id: 'Generic_PhoneNumber',pid: 'Only4NLU'},
  {id: 'Generic_Person',pid: 'Only4NLU'},
  {id: 'Generic_LocationType',pid: 'Only4NLU'},
  {id: 'Generic_Location',pid: 'Only4NLU'},
  {id: 'Generic_Language',pid: 'Only4NLU'},
  {id: 'Generic_IntNumber',pid: 'Only4NLU'},
  {id: 'Generic_FmName',pid: 'Only4NLU'},
  {id: 'Generic_FmFrequency',pid: 'Only4NLU'},
  {id: 'Generic_Duration',pid: 'Only4NLU'},
  {id: 'Generic_DeviceName',pid: 'Only4NLU'},
  {id: 'Generic_Date',pid: 'Only4NLU'},
  {id: 'Generic_CameraMode',pid: 'Only4NLU'},
  {id: 'Generic_CameraLens',pid: 'Only4NLU'},
  {id: 'Generic_AppType',pid: 'Only4NLU'},
  {id: 'Generic_AppName',pid: 'Only4NLU'},
  {id: 'Facebook_MessageCancel',pid: 'Facebook'},
  {id: 'Facebook_MessageAck',pid: 'Facebook'},
  {id: 'Facebook_MessageSend',pid: 'Facebook'},
  {id: 'Translate_Translate',pid: 'Translate'},
  {id: 'Vskit_TakeVideo',pid: 'Vskit'},
  {id: 'Vskit_Search',pid: 'Vskit'},
  {id: 'Calculator_OrdinaryCalculate',pid: 'Calculator'},
  {id: 'Calculator_CurrencyConversion',pid: 'Calculator'},
  {id: 'Calculator_UnitConversion',pid: 'Calculator'},
  {id: 'Joke_Play',pid: 'Joke'},
  {id: 'Generic_All',pid: 'Generic'},
  {id: 'Generic_Complaint',pid: 'Generic'},
  {id: 'Generic_Play',pid: 'Generic'},
  {id: 'Generic_OridinalNum',pid: 'Generic'},
  {id: 'Generic_Help',pid: 'Generic'},
  {id: 'Generic_No',pid: 'Generic'},
  {id: 'Generic_Yes',pid: 'Generic'},
  {id: 'Generic_Delete',pid: 'Generic'},
  {id: 'Generic_Cancel',pid: 'Generic'},
  {id: 'Generic_Send',pid: 'Generic'},
  {id: 'Generic_Resume',pid: 'Generic'},
  {id: 'Generic_Previous',pid: 'Generic'},
  {id: 'Generic_Next',pid: 'Generic'},
  {id: 'Generic_Stop',pid: 'Generic'}
]

var SlotsRows =[
  {pid: 'Audio_MusicPlay', vals: ['None', 'MusicName', 'Album', 'Artist', 'Playlist', 'Style', 'Band', 'MusicMode', 'GenericDate']},
  {pid: 'Audio_MusicAdd', vals: ['None', 'Playlist', 'MusicName']},
  {pid: 'Video_Play', vals: ['None', 'VideoName', 'Actor', 'GenericDate', 'Style', 'Director', 'GenericCountry', 'GenericKeyword']},
  {pid: 'Camera_SwitchMode', vals: ['None', 'Playlist', 'MusicName']},
  {pid: 'Camera_SwitchCamera', vals: ['None', 'CameraLens']},
  {pid: 'Camera_TakePhoto', vals: ['None']},
  {pid: 'Camera_TakeSelfie', vals: ['None']},
  {pid: 'Camera_TakeVideo', vals: ['None']},
  {pid: 'Camera_OpenCamera', vals: ['AppName(MH)']},
  {pid: 'Launcher_AppOpen', vals: ['None', 'AppName', 'AppType']},
  {pid: 'Launcher_AppUpdate', vals: ['None', 'AppName']},
  {pid: 'Launcher_AppSearch', vals: ['None', 'AppName', 'AppType']},
  {pid: 'Launcher_AppDownload', vals: ['None', 'AppName', 'AppType']},
  {pid: 'Launcher_AppDelete', vals: ['None', 'AppName']},
  {id: 'Device_SettingsOn', vals: ['None', 'DeviceName']},
  {id: 'Device_SettingsOff', vals: ['None', 'DeviceName']},
  {id: 'Device_VolumeDecrease', vals: ['None']},
  {id: 'Device_VolumeIncrease', vals: ['None']},
  {id: 'Device_VolumeSet', vals: ['None', 'GenericIntNum']},
  {id: 'Device_VolumeMute', vals: ['None']},
  {id: 'Device_VolumeUnmute', vals: ['None']},
  {id: 'Device_VolumeMax', vals: ['GenericMax(OH)', 'GenericIntNum(OH)']},
  {id: 'Device_VolumeMin', vals: ['GenericMin(OH)', 'GenericIntNum(OH)']},
  {id: 'Device_BrightnessDecrease', vals: ['None']},
  {id: 'Device_BrightnessIncrease', vals: ['None']},
  {id: 'Device_BrightnessSet', vals: ['None', 'GenericIntNum']},
  {id: 'Device_BrightnessMax', vals: ['GenericMax(OH)', 'GenericIntNum(OH)']},
  {id: 'Device_BrightnessMin', vals: ['GenericMin(OH)', 'GenericIntNum(OH)']},
  {id: 'Device_NodisturbON', vals: ['None']},
  {id: 'Device_NodisturbOff', vals: ['None']},
  {id: 'Device_Poweroff', vals: ['None']},
  {id: 'Device_PoweroffYes', vals: ['None']},
  {id: 'Device_PoweroffNo', vals: ['None']},
  {id: 'Device_SwitchSystemLanguage', vals: ['None', 'Language']},
  {id: 'Device_SchedulePowerOn', vals: ['None', 'GenericDate', 'GenericTime', 'AlarmType']},
  {id: 'Device_SchedulePowerOff', vals: ['None', 'GenericDate', 'GenericTime', 'AlarmType']},
  {id: 'Device_ScreenUseTime', vals: ['None']},
  {pid: 'Clock_TimeGet',vals: ['None', 'GenericLocation']},
  {pid: 'Clock_DateGet',vals: ['None', 'GenericDate', 'GenericLocation']},
  {pid: 'Clock_AlarmCheck',vals: ['None', 'GenericDate', 'GenericTime']},
  {pid: 'Clock_AlarmSet',vals: ['None', 'GenericDate', 'GenericTime', 'AlarmType']},
  {pid: 'Clock_AlarmUnset',vals: ['None', 'GenericDate', 'GenericTime', 'GenericOrdinalNum', 'GenericAll']},
  {pid: 'Clock_AlarmDelete',vals: ['None', 'GenericDate', 'GenericTime', 'GenericOrdinalNum', 'GenericAll']},
  {pid: 'Clock_TimerSet',vals: ['None', 'GenericDuration']},
  {pid: 'Clock_TimerReplace',vals: ['None']},
  {pid: 'Clock_TimerKeep',vals: ['None']},
  {pid: 'Communication_PhoneDial',vals: ['None', 'GenericPerson', 'PhoneNum', 'GenericOrdinalNum']},
  {pid: 'Communication_PhoneRedial',vals: ['None']},
  {pid: 'Communication_PhoneAnswer',vals: ['None']},
  {pid: 'Communication_PhoneReject',vals: ['None']},
  {pid: 'Communication_PhoneCheck',vals: ['None', 'GenericPerson', 'AppName(OH)']},
  {pid: 'Communication_MessageSend',vals: ['None', 'GenericPerson', 'GenericContent', 'PhoneNum', 'GenericOrdinalNum']},
  {pid: 'Communication_MessageAck',vals: ['None']},
  {pid: 'Communication_MessageCancel',vals: ['None']},
  {pid: 'Notes_Show',vals: ['None', 'NotesKeyword', 'NotesShowType']},
  {pid: 'Notes_Add',vals: ['None', 'GenericContent']},
  {pid: 'Notes_Delete',vals: ['None', 'NotesKeyword']},
  {pid: 'Weather_Forecast',vals: ['None', 'GenericLocation', 'GenericDate', 'DateType']},
  {pid: 'Weather_Temperature',vals: ['None', 'GenericLocation', 'GenericDate', 'DateType']},
  {pid: 'News_Play',vals: ['None', 'NewsKeyword', 'GenericLocation', 'GenericDate', 'NewsType']},
  {pid: 'FM_Modulation',vals: ['FmName', 'FmFrequency']},
  {pid: 'Whatsapp_MessageSend',vals: ['None', 'GenericContent', 'GenericPerson', 'AppName(MH)']},
  {pid: 'Whatsapp_MessageAck',vals: ['AppName(MH)']},
  {pid: 'Whatsapp_MessageCancel',vals: ['AppName(MH)']},
  {pid: 'Whatsapp_AudioCall',vals: ['None', 'GenericPerson', 'AppName(MH)']},
  {pid: 'Whatsapp_VideoCall',vals: ['None', 'GenericPerson', 'AppName(MH)']},
  {pid: 'Whatsapp_Dynamic',vals: ['AppName(MH)']},
  {pid: 'Whatsapp_Delete',vals: ['None', 'GenericPerson', 'AppName(MH)']},
  {pid: 'Whatsapp_PhotoSend',vals: ['None', 'GenericPerson', 'AppName(MH)']},
  {pid: 'Whatsapp_PhotoAck',vals: ['AppName(MH)']},
  {pid: 'Whatsapp_PhotoCancel',vals: ['AppName(MH)']},
  {pid: 'Calendar_Show',vals: ['None', 'GenericDate', 'GenericTime']},
  {pid: 'Calendar_Add',vals: ['None', 'GenericDate', 'GenericTime', 'GenericContent']},
  {pid: 'Calendar_Delete',vals: ['None', 'GenericDate', 'GenericTime']},
  {pid: 'Navigation_Start',vals: ['None', 'SrcLocation', 'DstLocation', 'ByLocation', 'NaviType', 'CustomLocation']},
  {pid: 'Navigation_Stop',vals: ['None']},
  {pid: 'Navigation_CurrentLocation',vals: ['None']},
  {pid: 'Navigation_Search',vals: ['None', 'NavSearchKeyword', 'LocationType', 'GenericLocation']},
  {pid: 'Web_Search',vals: ['None', 'GenericContent']},
  {pid: 'Ticket_Reservation',vals: ['None', 'VehicleType', 'SrcLocation', 'DstLocation', 'GenericDate', 'GenericTime', 'GenericPerson']},
  {pid: 'Faq_WhoIAm',vals: ['None']},
  {pid: 'Faq_WhoYouAre',vals: ['None']},
  {pid: 'Faq_MissElla',vals: ['None']},
  {pid: 'Faq_AskSkill',vals: ['None']},
  {pid: 'Faq_AskSingOrNot',vals: ['None']},
  {pid: 'Faq_AskGender',vals: ['None']},
  {pid: 'Faq_AskFather',vals: ['None']},
  {pid: 'Faq_AskMother',vals: ['None']},
  {pid: 'Faq_AskAge',vals: ['None']},
  {pid: 'Faq_HelloElla',vals: ['None']},
  {pid: 'Generic_DateTypeLocation',vals: ['DateType', 'GenericLocation']},
  {pid: 'Generic_DateLocation',vals: ['GenericDate', 'GenericLocation']},
  {pid: 'Generic_DateTime',vals: ['GenericDate', 'GenericTime']},
  {pid: 'Generic_DateType',vals: ['DateType']},
  {pid: 'Generic_CalculateContent',vals: ['CalculateContent']},
  {pid: 'Generic_CustomLocation',vals: ['CustomLocation']},
  {pid: 'Generic_Time',vals: ['GenericTime']},
  {pid: 'Generic_PhoneNumber',vals: ['PhoneNum']},
  {pid: 'Generic_Person',vals: ['GenericPerson']},
  {pid: 'Generic_LocationType',vals: ['LocationType']},
  {pid: 'Generic_Location',vals: ['GenericLocation']},
  {pid: 'Generic_Language',vals: ['Language']},
  {pid: 'Generic_IntNumber',vals: ['GenericIntNum']},
  {pid: 'Generic_FmName',vals: ['FmName']},
  {pid: 'Generic_FmFrequency',vals: ['FmFrequency']},
  {pid: 'Generic_Duration',vals: ['GenericDuration']},
  {pid: 'Generic_DeviceName',vals: ['DeviceName']},
  {pid: 'Generic_Date',vals: ['GenericDate']},
  {pid: 'Generic_CameraMode',vals: ['CameraMode']},
  {pid: 'Generic_CameraLens',vals: ['CameraLens']},
  {pid: 'Generic_AppType',vals: ['AppType']},
  {pid: 'Generic_AppName',vals: ['AppName']},
  {pid: 'Facebook_MessageCancel',vals: ['AppName(MH)']},
  {pid: 'Facebook_MessageAck',vals: ['AppName(MH)']},
  {pid: 'Facebook_MessageSend',vals: ['None', 'GenericPerson', 'GenericContent', 'AppName(MH)']},
  {pid: 'Translate_Translate',vals: ['None', 'GenericContent', 'Language']},
  {pid: 'Vskit_TakeVideo',vals: ['None']},
  {pid: 'Vskit_Search',vals: ['None', 'VskitKeyword']},
  {pid: 'Calculator_OrdinaryCalculate',vals: ['CalculateContent']},
  {pid: 'Calculator_CurrencyConversion',vals: ['None']},
  {pid: 'Calculator_UnitConversion',vals: ['None']},
  {pid: 'Joke_Play',vals: ['None', 'JokeKeyword', 'JokeType']},
  {pid: 'Generic_All',vals: ['None']},
  {pid: 'Generic_OridinalNum',vals: ['GenericOrdinalNum']},
  {pid: 'Generic_Complaint',vals: ['None']},
  {pid: 'Generic_Play',vals: ['None']},
  {pid: 'Generic_Help',vals: ['None']},
  {pid: 'Generic_No',vals: ['None']},
  {pid: 'Generic_Yes',vals: ['None']},
  {pid: 'Generic_Delete',vals: ['None', 'GenericOrdinalNum', 'GenericAll']},
  {pid: 'Generic_Cancel',vals: ['None', 'GenericOrdinalNum', 'GenericAll']},
  {pid: 'Generic_Send',vals: ['None']},
  {pid: 'Generic_Resume',vals: ['None', 'MediaType']},
  {pid: 'Generic_Previous',vals: ['None', 'MediaType']},
  {pid: 'Generic_Next',vals: ['None', 'MediaType']},
  {pid: 'Generic_Stop',vals: ['None', 'MediaType']}
]

export {domainRows, intentRows, SlotsRows}